trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  - name: modulePath
    value: Hello

steps:
- task: PowerShell@2
  displayName: 'Download nuget.exe'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -ItemType Directory -Path tools -Force
      Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile tools\nuget.exe
- task: PowerShell@2
  displayName: 'Create module nuspec'
  inputs:
    targetType: 'inline'
    script: |
      Set-Location $(modulePath)
      $moduleName = (Get-Item .).Name
      $moduleManifest = Get-Item -Path "*.psd1"
      $moduleVersion = (Import-PowerShellDataFile -Path $moduleManifest.FullName).ModuleVersion
      
      (Get-Content "Package.nuspec") -replace '{id}', $moduleName -replace '{version}', $moduleVersion | Set-Content "$moduleName.nuspec"
      Remove-Item "Package.nuspec"
- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'

- task: NuGetCommand@2
  displayName: 'Push module to Azure DevOps Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.Repository.LocalPath)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'LongjunTest/ps-private-module'